name: Test Auth Firefox

on:
  push:
    branches: ['**']

jobs:
  test-firefox:
    name: Test Auth on Firefox Unit Browser
    runs-on: ubuntu-latest

    steps:
      - name: install Firefox stable
        run: |
          sudo apt-get update
          sudo apt-get install firefox
      - uses: actions/checkout@v2
      - name: Set up Node (14)
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Bump Node memory limit
        run: echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV
      - name: Test setup and yarn install
        run: |
          cp config/ci.config.json config/project.json
          yarn
      - name: build
        run: yarn build
      - name: Run tests on changed packages
        run: xvfb-run yarn --cwd packages/auth test:browser:unit
        env:
          BROWSERS: 'Firefox'
